### PR TITLE
feature: explicitly sign disabled fields.

### PR DESCRIPTION
**Pull request by jamesmoriarty**

### CODE REVIEW

**Comment by garrow** [comment]
Might not be as much as you think.

```shell
> ack permit_all
spec/controllers/profiles/suppliers_controller_spec.rb
70:        permit_all_parameters

spec/controllers/profiles/travellers/offline_bookings_controller_spec.rb
14:      permit_all_parameters

spec/controllers/trips/segments/hotels_controller_spec.rb
20:    ActionController::Parameters.permit_all_parameters = true

spec/controllers/trips/segments/vehicles_controller_spec.rb
20:    ActionController::Parameters.permit_all_parameters = true

spec/controllers/trips/universal_records_controller_spec.rb
11:      permit_all_parameters

spec/support/shared/examples/controllers/inherited_resources.rb
181:    permit_all_parameters

spec/support/shared/examples/controllers/readonly_inputs.rb
77:    permit_all_parameters
```

**Comment by Spaceghost** [comment]
@jamesmoriarty, can you add a test case for this? If you need help, I'm available to pair on it at some point soon.

@garrow I'm not sure I understand what you're getting at, can you explain what you mean?

**Comment by jamesmoriarty** [comment]
@Spaceghost I'll do that. I think this behaviour might be considered unexpected to some. Maybe `signed: false` should be past instead.

**Comment by Spaceghost** [comment]
@jamesmoriarty If I understand the code correctly, the point is to be able to have disabled fields in your form that you don't want signed and don't want to have to reject, right?

I can't think up a case where I'd have a form that includes disabled fields that I'd want to be sent back. If you were to have disabled fields that you'd enable later, I'd imagine you'd disable the fields with JS so that no-js consumers can fill out the field without requiring JS.

Does that make sense?

**Comment by jamesmoriarty** [comment]
@Spaceghost that is correct.

**Comment by Spaceghost** [comment]
@jamesmoriarty I think that makes perfect sense for that to be the default behaviour. In addition to some tests, do you maybe want to add that to the README?

**Comment by jamesmoriarty** [comment]
Just doing that now.

**Comment by jamesmoriarty** [comment]
@Spaceghost Done. Thanks for the feedback.

**Comment by Spaceghost** [comment]
@jamesmoriarty Thanks for the great pull request. It looks good.

**Comment by Spaceghost** [comment]
@jamesmoriarty I'll have to wait a little bit to release the gem. @erichmenge needs to enable me to release to rubygems.

**Comment by jamesmoriarty** [comment]
No worries. I understand.

**Pull request merged**
