### PR TITLE
Release attempt

### LINKED ISSUE #30: New Gem Releases?
I noticed there is a 0.3 and 0.4 version in the repo but neither are on Rubygems.

### PR DESCRIPTION
**Pull request by eric1234**
This is an attempt to help get a new release out the door and close several issues and PR. My own #30 asking for a new release started this. @Spaceghost asked if someone could package the gem up and send to them. I was originally just going to cut version 0.4.0 as is but there are some important fixes that if incorprated would clean up things a bit.

* This PR starts at master.
* I then merged in #25 by @schuetzm to help fix up the tests.
* I also merged in #29 also by @schuetzm to remove a deprecation warning.
* I tried to merge in @tubbo's #28 but it causes test failures and it wasn't obvious how to solve. Basically the requests he is creating are getting an error because it they don't have a proper form signature param.
* When testing against Rails `master` the new `form_with`/`fields` that are replacing `form_for`/`fields_for` caused an error.  8517af8 fixes the error but doesn't add proper support for `form_with`/`fields`. See that commit message for rational.
* `9985314` removed some rspec deprecations warnings. The process of that revealed a bug in the test which was fixed.
* `63b99fb` is just some debugging help I needed and I left it there to help others.
* `b263e5b` enhances the Gemfile so I could test against Rails 5 stable. It also makes it so that as new Rails versions are released we don't need to change this file as often. I also removed special support for Rails 3 completely and proposed we only support whatever Rails itself supports. See that commit message for furhter details.
* `c6a3dcb` bumps the version number in the hopes that all this will get a new release out the door. Per @Spaceghost request on #30 I am [attaching a gem](https://github.com/erichmenge/signed_form/files/722222/signed_form-0.5.0.gem.zip) that can be uploaded to RubyGems (had to zip it to get it to upload to GitHub).

Overall, this seems like a lot of changes but it's really just fixing tests and removing deprecation warnings. The runtime code should be the same as in master. Once accepted it will close #30, close #25 and close #29.

### CODE REVIEW

**Comment by schuetzm** [comment]
I'm using this version in production (albeit on an infrequently used site), and haven't found any problems so far. And the rspec tests pass as well, so I think we can trust this to be ok.

Unfortunately signed_form was dropped from Travis; could someone reenable it, please?

**Comment by schuetzm** [comment]
@Spaceghost Can you merge this? Or can you give me commit access to this repo and add me as a maintainer on rubygems.org?

**Comment by Spaceghost** [comment]
@schuetzm I can't add anyone, I can merge, and I have release privileges. Can we coordinate over discord or something and get what we can done until we can get you commit and release privileges?

**Comment by Spaceghost** [comment]
I'm unpacking and inspecting the uploaded gem before I attempt to get it pushed to rubygems proper.

Thank you for your work @eric1234 and @schuetzm!

**Pull request merged**
