### PR TITLE
Pivot to GitHub Actions

### PR DESCRIPTION
**Pull request by leoarnold**
In late 2020, Travis CI decided to discontinue unlimited free builds for public projects. While they still hand out free build minutes for opensource project, they do this through an application process, thereby making it difficult to quickly contribure:

https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Since GitHub Actions still allows unlimited build time for public project, it became the go-to CI for opensource projects on GitHub.

We also update the test build to include contemporary versions of Ruby.

### CODE REVIEW

**Comment by leoarnold** [comment]
@erichmenge Is this project still maintained? Last commit in master branch is five years old.

**Comment by Spaceghost** [comment]
@leoarnold first, thank you for the PR. A few of us that I know of have been using this gem at our places of work. I ought to have a branch with the taint fix, or I'll push it up when I find which machine it's on.

I've also got a branch that builds faas functions you can deploy for different platforms (aws & cloudflare) which handles unsigned and modified/malformed form detection&rejection at the edge that compliments the rack middleware pretty well.

If you want to keep making pull requests, I'll push them on through with you, but I'd also be happy to have another maintainer to the repo if you wanted to grab a chat and coordinate getting you onboard. You can email me AT spaceghost.st unless you'd prefer something else.

I'm glad to meet you, @leoarnold.

~Spaceghost

**Comment by leoarnold** [comment]
Thanks @Spaceghost . I sent this PR as a kind of "test balloon" to see if the project is still alive - and after two months without attention, I removed the gem from our work project.

There was also a problem where `singed_form` worked with Rails 6.0 and Rails 7.0, but not Rails 6.1. It has to do with the use of `Marshal.dump(model)` to create a checksum, which will not work if the object to be marshaled contains a `Proc`. I never got to the root of that, though.

**Comment by Spaceghost** [comment]
@leoarnold definitely understandable. I appreciate the time you spent with it!

**Pull request merged**
