### PR TITLE
Use Rails' `secret_key_base` as signing key if available

### PR DESCRIPTION
**Pull request by schuetzm**

### CODE REVIEW

**Comment by Spaceghost** [comment]
@schuetzm Seems entirely innocuous. Can you imagine a case where a rails application would change its secret key base without redeploying or otherwise possibly causing signed_form to use an old key that was supposed to be removed? What do you think about delegating unless it's not there in the first place?

**Comment by schuetzm** [comment]
I don't think that's officially supported, because the secrets are stored in `secrets.yml`, which is only read once at start up. The docs don't say anything about changing it at runtime either.

I've only seen a recommendation to change it in order to invalidate cookies that became invalid after an upgrade, but that's an infrequent affair and includes a restart of rails. I also find it unlikely that someone changes the secrets regularly, because that would invalidate all cookies from before the change, even if the had just been created a few seconds earlier. What use could that have?

**Comment by Spaceghost** [comment]
I think you're right. What I was considering was a possible case where one perhaps does a data migration of some kind and needs to invalidate the keys, but it seems like the most likely path forward they'd take is just to change the key and redeploy/restart their app anyways.

:+1:

**Comment by Spaceghost** [comment]
I'm stuck trying to release the gem, just wanted to give an update on that. Working it out.

**Comment by schuetzm** [comment]
Anything new here?

**Pull request merged**
