### PR TITLE
Ignore anchor in URL validation

### LINKED ISSUE #27: An anchor in URL
I have a form with anchor:

``` ruby
= simple_form_for resource, url: resource_path(resource, anchor: 'form-update'), html: { id: 'form-update' }, method: 'put' do
...
```

And when I submit it I get an error:

```
SignedForm::Errors::InvalidURL - SignedForm::Errors::InvalidURL:
  signed_form (0.2.0) lib/signed_form/gate_keeper.rb:35:in `verify_destination'
  signed_form (0.2.0) lib/signed_form/gate_keeper.rb:11:in `initialize'
  signed_form (0.2.0) lib/signed_form/action_controller/permit_signed_params.rb:18:in `permit_signed_form_data'
```

I don't know exactly how much it correct but maybe skip a anchor? Like this:

```
    def verify_destination
      return unless options[:method] && options[:url]
      raise Errors::InvalidURL if options[:method].to_s.casecmp(@request.request_method) != 0
      controller_url = @controller.url_for(options[:url])
      url = URI.parse(controller_url).path
      raise Errors::InvalidURL if url != @request.fullpath && url != @request.url
    end
```

### PR DESCRIPTION
**Pull request by tubbo**
Since the anchor portion of a URL is not processed by the server anyway,
it should not be taken into account when we validate the URL that the
form data is being sent to.

Fixes #27

### CODE REVIEW

**Comment by Spaceghost** [comment]
@tubbo this is looking pretty good, chum. I've still not gotten a local development environment fully running so I can run the test suite though. I'll merge this the moment I figure it out.

**Comment by Spaceghost** [comment]
@tubbo Would you be interested in taking another stab at this?

**Comment by tubbo** [comment]
@Spaceghost should be good to go, I updated tests to match the changes in the codebase.

**Comment by Spaceghost** [comment]
@tubbo Thanks, sir! I'm going to have some words with the merge request button
and then get another release pushed out quick-fast. What do you think, bug or
feature? I'm inclined to call it a feature so we can keep moving forward and
call it an additional win rather than a defect from intended design.

**Comment by Spaceghost** [comment]
@tubbo I'm eager to cut a version for the last legacy version before only supporting latent rubies and rails versions. What do you think we should do for the version, feature sound fair?

**Comment by tubbo** [comment]
@Spaceghost I don't think this should be in the legacy versions of signed_form because it changes how form tokens are created, thus breaking older forms if you update the gem and e.g. don't clear caches or something.

**Review by Alexandrag88 — APPROVED** [review]

**Pull request merged**
